#!/bin/bash

# A A Omoware
# Creates a new gists
# https://developer.github.com/v3/auth/
# https://developer.github.com/v3/gists/
#------------------------------------------

# simulate a new gist
function create_new_gists () {
	curl \
		--user "$GIST_user:$token" \
		--request POST \
		--data '{"description":"equalexperts test","public":"true","files":{"eq.txt":{"content":"equalexperts test"}}' $GIST_api
}

#----
red='\033[0;31m'
default='\033[0m'
GIST_api="https://api.github.com/gists"

if [ "$#" -gt "1" ] 
	then
		GIST_user=$1
		token=$2
else
	echo -e "\n${red}Both github username & token are needed${default}\n"
	exit 1
fi

create_new_gists
exit 0
